version: '3'
services:
    server:
        image: "grigiu/sftp:latest"
        restart: always
        environment:
          SSH_MASTER_USER: "master"
          SSH_MASTER_PASS: "master"
        hostname: server
        ports:
            - "2222:22"
        volumes:
            - ./uploads:/uploads
